version: '0.1'
services:
  scraper:
    build: .
    container_name: downloader
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://mohammad:30676@db:3306/downloader
      - TZ=Asia/Tehran
    volumes:
      - /etc/localtime:/etc/localtime:ro

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "30676"
      MYSQL_USER: mohammad
      MYSQL_PASSWORD: "30676"
      MYSQL_DATABASE: downloader
    ports:
      - "3306:3306"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
