name: Test SSH connection

on:
  workflow_dispatch:

jobs:
  test_ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and say hi
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "✅ SSH connection established"
            uname -a
